version: "3.9"

services:
  db:
    image: postgres:12
    restart: always
    container_name: integration-tests-prisma
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
      POSTGRES_DB: tests

  redis:
    image: redis:5-alpine
    restart: always
    container_name: integration-tests-redis
    ports:
      - "6380:6379"

  erica-mock:
    image: ghcr.io/digitalservicebund/erica-mock:57d950f497b53d1a7792b896492ad562dbb5ef58
    restart: always
    container_name: erica-mock
    ports:
      - "8001:8000"
