version: "3.9"

services:
  db:
    image: postgres:12
    restart: always
    container_name: integration-tests-prisma
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
      POSTGRES_DB: tests

  erica-mock:
    image: ghcr.io/digitalservicebund/erica-mock:d7831058fc2562562a7c004d62c9977e1e4a79b4
    restart: always
    container_name: erica-mock
    ports:
      - "8001:8000"
