version: "3.9"

services:
  db:
    image: postgres:12
    restart: always
    container_name: integration-tests-prisma
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
      POSTGRES_DB: tests

  erica-mock:
    image: ghcr.io/digitalservicebund/erica-mock:1db8b487f6c4ac2d1eb9d60e0ee60f709724177f
    restart: always
    container_name: erica-mock
    ports:
      - "8001:8000"
