version: "3.9"

services:
  db:
    image: postgres:12
    restart: always
    container_name: integration-tests-prisma
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
      POSTGRES_DB: tests

  erica-mock:
    image: ghcr.io/digitalservicebund/erica-mock:latest
    restart: always
    container_name: erica-mock
    ports:
      - "8000:8000"
